image: maven:3.3.9-jdk-8

before_script:
  - |
    cd /builds/abidkidwai786/LT-appium-java
    echo 'export LT_USERNAME=LT_username' >> ~/.bashrc
    echo 'export LT_ACCESS_KEY=LT_access_key' >> ~/.bashrc

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn clean install
  tags:
    - docker
    - gce
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

test:
  stage: test
  script:
    - mvn test -P android
  tags:
    - docker
    - gce
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
